#!/usr/bin/env bash
#
# make-dev-twin.sh — genera el "gemelo dev" del nodo a partir del codigo real.
#
# El gemelo es un paquete npm separado (n8n-nodes-agent-langfuse-dev) que puede
# convivir con el nodo de produccion en la MISMA instancia de n8n. Para ello
# reescribe 3 identificadores sobre una copia del codigo (sin duplicar fuente):
#   - nombre del paquete:   n8n-nodes-agent-langfuse -> n8n-nodes-agent-langfuse-dev
#   - nombre de credencial: agentLangfuseApi         -> agentLangfuseApiDev
#   - nombre del nodo:       agentLangfuse            -> agentLangfuseDev
# (la credencial DEBE renombrarse: n8n indexa credenciales por 'name' sin
#  namespace de paquete, asi que compartir 'agentLangfuseApi' colisiona con prod).
#
# Uso:   scripts/make-dev-twin.sh [version]
#   version por defecto: 0.3.0-dev.0
#
# Produce .dev-twin/n8n-nodes-agent-langfuse-dev-<version>.tgz (gitignored).
#
# LOCAL ONLY. El tarball se instala por CLI dentro del contenedor de n8n; no se
# publica en ningun registro. Lo estuvo, y fue un error: el gemelo heredaba el
# keyword n8n-community-node-package y aparecia en las busquedas de community
# nodes junto al paquete real, con el README del paquete real. El paso 3 marca
# el paquete como private y le quita los keywords para que npm publish lo rechace.
set -euo pipefail

VER="${1:-0.3.0-dev.0}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.dev-twin"

echo ">> generando gemelo dev  version=$VER"
rm -rf "$OUT"
mkdir -p "$OUT"

# 1) copiar fuente (sin node_modules/dist/.git); reutilizar deps por symlink
cp -a "$ROOT/nodes" "$ROOT/credentials" "$ROOT/test" \
      "$ROOT/tsconfig.json" "$ROOT/package.json" "$ROOT/README.md" "$ROOT/LICENSE" \
      "$OUT/"
ln -s "$ROOT/node_modules" "$OUT/node_modules"

cd "$OUT"

# 2) reescribir identificadores en el codigo
#    - credencial: todas las apariciones del literal 'agentLangfuseApi' (con comillas)
#      cubren el name del credential type, el array credentials del nodo y los
#      getCredentials(). NO toca langfuseApiRequest (sin comillas) ni comentarios.
grep -rl "'agentLangfuseApi'" nodes credentials | xargs sed -i "s/'agentLangfuseApi'/'agentLangfuseApiDev'/g"
#    - credencial: displayName
sed -i "s/displayName = 'Agent Langfuse API'/displayName = 'Agent Langfuse API (dev)'/" \
  credentials/AgentLangfuseApi.credentials.ts
#    - nodo: name + displayName + defaults.name
sed -i "s/name: 'agentLangfuse'/name: 'agentLangfuseDev'/" \
  nodes/AgentLangfuse/AgentLangfuse.node.ts
sed -i "s/displayName: 'AI Agent + Langfuse'/displayName: 'AI Agent + Langfuse (dev)'/" \
  nodes/AgentLangfuse/AgentLangfuse.node.ts
sed -i "s/name: 'AI Agent + Langfuse'/name: 'AI Agent + Langfuse (dev)'/" \
  nodes/AgentLangfuse/AgentLangfuse.node.ts

# 3) reescribir package.json: nombre, version, y blindaje contra publicacion
#    - private:true -> npm publish lo rechaza (npm pack sigue funcionando)
#    - sin keywords -> no aparece como community node en las busquedas de npm
VER="$VER" node -e '
  const fs = require("fs");
  const p = JSON.parse(fs.readFileSync("./package.json", "utf8"));
  p.name = "n8n-nodes-agent-langfuse-dev";
  p.version = process.env.VER;
  p.description = "[DEV TWIN] local-only test build. Never publish.";
  p.private = true;
  p.keywords = [];
  delete p.publishConfig;
  fs.writeFileSync("./package.json", JSON.stringify(p, null, 2) + "\n");
'

# 3b) README de aviso, para que nadie confunda el gemelo con el paquete real
cat > README.md <<'TWINREADME'
# n8n-nodes-agent-langfuse-dev

Local-only test build of [n8n-nodes-agent-langfuse](https://github.com/Diward/n8n-nodes-agent-langfuse).

It renames the package, the node (`agentLangfuseDev`) and the credential
(`agentLangfuseApiDev`) so a release candidate can be installed next to the real
node in a single n8n instance. It is generated by `scripts/make-dev-twin.sh` and
is marked `private`, so it must never reach a registry.

Install the real node instead: `npm install n8n-nodes-agent-langfuse`
TWINREADME

# 4) build + pack
npm run build >/dev/null
npm pack

echo ">> hecho:"
ls -1 "$OUT"/*.tgz
